version: '2'

volumes:
    db:
      driver: local

services:
  modx:
    build: .
    container_name: modx
    hostname: modx
    user: root
    restart: always
    ports:
          - "443:443"
          - "80:80"
#          - "81:80"
    volumes:
        - ./app:/var/www/html
        - ./nginx:/etc/nginx/conf.d/
        - ./certs/letsencrypt:/etc/letsencrypt
        - ./certs/ssl:/etc/nginx/ssl
        - ./cron:/var/spool/cron/crontabs

    entrypoint: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n
