language: python
python:
- 2.7
env:
  matrix:
  - DOCKER_CONTENT_TRUST=0
  global:
  - secure: OJ8+SN0Q1/gx9lT3D7kRGdU0RQ2qMoszIpVRfc1iAU9qqhaEdw5rFACv+soHvWASmP7KQrqtJiw2NmnWuXbK6l+LcBmbsT3kS0o8d+0Quzb7N65vQVNmrCs9eKq1esJv7xi7ovXM9ucqjBqav3PTRgRLgG9GfLEeBEN0FBOY/oDrTHi735vMGUfQMkHn2WgHisciOvRRBU9z+UZlEOb+WOmA0ainn7t4e/yasz4ZQdzDNkcp5EfCquz+Sl+H2oBJzpDU/DYjweg07FdNuNuQ6Es8E2cCTDVMnlF+UnUIcq95AG1RW9YJ2HFvr2jaDEnikbpaxjobqJG5e28JdKHuu1UYwizmNFdECbTiftgi1O1RHdRhlEzMmmaxbzgqsjukYMgpZxiLn+Oowyfs15KRjRARJ5Z0zYUtReB71sfk4VtVw//vSDvIIG0qNrRp5IPzA30jEc1wBcBm27R499udN4pZ6WRvDpetiSY2bTTC4M8nVwccp9XsjOf1yLJnjp/EZ+coWs4eDo29ysrv94qYcx/1aVath5IxieiJQxfcOt5y509OwAStOVOJiaqAnYkpg990ONG3OraN5N9HIDsRCDn4R93sbzC8DWNTmHJHwDLoPOd292qWRCarRp5uWyfbxak9GjBeIjjc+GpVUHMnb+wWKiAnlfYvz0PoDYpW7fE=
  - secure: Yv/iEF7LuXXjVvqzMbZ4Ac9rXi8lvpqLjgve+r/G3HNjLwZ9TKdTtkHjl2NHXpWxTYDXFLzurp/YhHMMfVuIV9t+GPkdfRULNaIlJ7WQZxSK4QM83UsDwIjQchv5EwdIq4QwC7f7bJQwiBGjqWm6LgNDniU2VLqfrtW5PoufjMqe9gbemkxJzhpCurlNCw0LO8WI5AEVLi3uFNZzy8HBj5I5tfbfaqMxI1T4GXp5IXcIgjtHPkpmX5i5V/H4VfqbUHdqJ5XQRpXtqf17ejtQL26gUGhyXa9krZrKO0wz7dIGtcAUnrKUrBGnlNVq285Ow4mexL1csPL+SbTLxj/DIqK8RQclQe39Hr53DvHE24ROvYaDHv3SZKxNdYobUst6c0lp7zOyR4ZU1NGE/E0sMzNYnwUiNNJZkk4gRrGkmMDZ4+GbLqz0PzLZYb46XdvTcQNYbzZC2ZB1ZAbVw/DdNFD+bo7UBqd5mgSqDq6tx84Wlfrna2W/qgeL4VAO1OgVRsh+RtXwizbFJDIRh/k8iMwWwhZBhkH3kfPTWV9RDhh/Nzg7Fehj/2C4MOIgp2ih7NCXtRqXvpDBxhPXFeAzW+VX1uECpchVtTLD/SvgkHWDygf8Pe0Re7ehht6JThE4vxX3XGdYS6SM2+w7+g5K+3tOgwxyF+nDvw/aRqPvnSY=
services:
- docker
before_install:
- sudo apt-get update
- docker-compose --version
- pip install docker-compose --upgrade
- docker-compose --version
install:
- cd v2_6_2/dockerfiles
- docker-compose build
- docker cp configs/config.xml /usr/src/modx-2.6.2-pl/
- docker-compose up -d
- docker-compose ps
before_script:
- pip install requests
- pip install docker
- cd $TRAVIS_BUILD_DIR
script:
- python tests.py
notifications:
  slack:
    rooms:
    - optimum-team:GycletOWK4Kt95GktwYwfUMp#build
after_success:
- cd v2_6_2/dockerfiles
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- docker-compose -f docker-compose-build.yml images
- docker push trydirect/modx:2.6.2
