version: '2'

volumes:
    modxdb:
      driver: local

services:
  modx:
    image: trydirect/modx:2.6.2
    build: builds
    container_name: modx
    hostname: modx
    user: root
    restart: always
    ports:
          - "80:80"
          - "443:443"
    working_dir: /var/www/html/modx-2.6.2-pl
    volumes:
        - ./app:/var/www/html/modx-2.6.2-pl
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./certs/letsencrypt:/etc/letsencrypt
        - ./certs/ssl:/etc/nginx/ssl
        - ./cron:/var/spool/cron/crontabs
    links:
        - modxdb
    env_file: .env
    entrypoint: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n

  modxdb:
    image: mysql:5.7
    container_name: modxdb
    restart: always
    volumes:
        - modxdb:/var/lib/mysql
    env_file: .env
