version: '2'

volumes:
    modxdb:
      driver: local

services:
  modx:
    image: trydirect/modx:2.6.2
    build: builds
    container_name: modx
    hostname: modx
    user: root
    restart: always
    ports:
          - "80:80"
    working_dir: /var/www/html/modx-2.6.2-pl
    volumes:
        - ./app:/var/www/html/modx-2.6.2-pl
        - ./configs/nginx/conf.d:/etc/nginx/conf.d
        - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./configs/certs/letsencrypt:/etc/letsencrypt
        - ./configs/certs/ssl:/etc/nginx/ssl
        - ./configs/cron:/var/spool/cron/crontabs
        - ./configs/modx/config.xml:/var/www/html/modx-2.6.2-pl/setup/config.xml
        - ./configs/php/fpm/php.ini:/etc/php/7.1/fpm/php.ini
        - ./configs/php/www.conf:/etc/php/7.1/fpm/pool.d/www.conf
    links:
        - modxdb
    env_file: .env
    entrypoint: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n

  modxdb:
    image: mysql:5.7
    container_name: modxdb
    restart: always
    volumes:
        - modxdb:/var/lib/mysql
    env_file: .env
